setw -g mode-keys vi
set -g mouse on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # colored underscores
set -as terminal-overrides ',alacritty:RGB' # true-color support
set-option -g focus-events on

# Characterwise selection
bind-key -T copy-mode-vi v send -X begin-selection

# Linewise selection
bind-key -T copy-mode-vi V send -X select-line

# Copy with Enter or y
bind-key -T copy-mode-vi Enter send -X copy-selection
bind-key -T copy-mode-vi y send -X copy-selection
